services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devDB
      POSTGRES_DB: dev
    networks:
      - local
networks:
  local:
