spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/dev
        username: dev
        password: devDB
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
